require ("plugs_config.habamax")
require ("plugs_config.telescope")
require ("plugs_config.treesitter")
require ("plugs_config.lsp_configs")
require ("plugs_config.statusline")
require ("plugs_config.tabline")
