require("plugs_config.color_scheme")
require("plugs_config.treesitter")
require("plugs_config.lsp_configs")
require("plugs_config.tabline")
require("plugs_config.format")
require("plugs_config.fzf")
require("plugs_config.autocmp")
