require("plugs_config.color_scheme")
require("plugs_config.telescope")
require("plugs_config.treesitter")
require("plugs_config.lsp_configs")
--require ("plugs_config.statusline")
require("plugs_config.tabline")
require("plugs_config.autocmp")
require("plugs_config.format")
